name: molpal-test

channels:
  - conda-forge
  - defaults

dependencies:
  - pytorch::pytorch >=1.10
  - pytorch::cpuonly
  - pip
  - rdkit
  - pip:
    - configargparse
    - h5py
    - numpy
    - ray >= 1.11
    - ray[tune]
    - pytest
    - pytorch-lightning
    - scikit-learn
    - tensorflow
    - tensorflow-addons
    - tqdm
