name: molpal

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - configargparse
  - h5py
  - importlib_resources
  - numpy=1.19
  - pip
  - python
  - pytorch
  - rdkit
  - scikit-learn
  - tqdm
  - pip:
    - tensorflow
    - tensorflow-addons
    - typing-extensions
