name: molpal

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - configargparse
  - h5py
  - importlib-resources
  - numpy
  - pip
  - python=3.6.10
  - pytorch
  - rdkit=2020.03.5
  - scikit-learn
  - tqdm
  - pip:
    - tensorflow
    - tensorflow-addons
    - typing-extensions
