name: molpal

channels:
  - conda-forge
  - defaults

dependencies:
  - conda-forge::cudatoolkit=11.1
  # - pytorch::cudatoolkit=10.2
  - configargparse
  - h5py
  - importlib_resources
  - numpy
  - python=3.8
  - pytorch::pytorch
  - rdkit
  - scikit-learn
  - tqdm
  - pip
  - pip:
    - ray
    - tensorflow
    - tensorflow-addons
    - typing-extensions
