name: multiscreen

channels:
  - conda-forge

dependencies:
  - nvidia::cudatoolkit # for cuda >= 11
  # - pytorch::cudatoolkit # for cuda < 11
  # - pytorch::cpuonly
  - python=3.8
  - pytorch::pytorch
  - pip
  - openbabel=3.1.1
  - rdkit=2021.03.3 
