name: dkenv

channels:
  - conda-forge
  - defaults

dependencies:
  # comment out the corresponding line for your specific CUDA version
  - nvidia::cudatoolkit=11.1
  # - pytorch::cudatoolkit=10.2
  # - pytorch::cpuonly
  - configargparse
  - h5py
  - importlib_resources
  - numpy
  - python=3.8
  - pytorch::pytorch
  - rdkit
  - scikit-learn
  - tqdm
  - pip
  - pip:
    - ray[default]
    - pytorch-lightning
    - tensorflow
    - tensorflow-addons
    - typing-extensions
