name: molpal

channels:
  - conda-forge
  - defaults

dependencies:
  # comment out the corresponding line for your specific CUDA version
  # - nvidia::cudatoolkit=11.1
  # - pytorch::cudatoolkit=10.2
  # - pytorch::cpuonly
  - python=3.8
  - pytorch::pytorch
  - rdkit
  - pip
  - pip:
    - configargparse
    - h5py
    - numpy
    - ray[default]
    - pytorch-lightning
    - scikit-learn
    - tensorflow
    - tensorflow-addons
    - tqdm
