name: molpal

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - configargparse
  - h5py
  - importlib_resources
  - numpy
  - omnia::pdbfixer
  - python=3.6.10
  - pytorch
  - rdkit
  - scikit-learn
  - tqdm
  - pip
  - pip:
    - tensorflow
    - tensorflow-addons
    - typing-extensions
